version: 2.1
jobs:
  BotMonitoring:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Run Python script
          command: python3 main.py $CR_Uname_xalta $CR_Pass_xalta $GsheetMainID_xalta
            $GsheetAlertID_xalta $EID_xalta $EPass_xalta $12 $password
workflows:
  version: 2
  commit-workflow:
    version: 2
    jobs:
      - BotMonitoring:
          filters:
            branches:
              only:
                - Lohith
