version: 2.1

jobs:
  BotMonitoring:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Run Python script
          command: python3 main.py

workflows:
  version: 2
  commit-workflow:
    jobs:
      - BotMonitoring
  schedule-BotMonitoring:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - BotMonitoring
