version: 2.1

jobs:
  BotMonitoring:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Run Python script
          command: |
            python3 main.py $anand

workflows:
  version: 2
  commit-workflow:
    jobs:
      - BotMonitoring:
          filters:
            branches:
              only:
                - main
