version: 2.1

jobs:
  BotMonitoring:
    docker:
      - image: circleci/python:3.9
    environment:
      anand: $anand
    steps:
      - checkout
      - run:
          name: Run Python script
          command: |
            echo "Running with control room username: $anand"
            python3 main.py

workflows:
  version: 2
  commit-workflow:
    jobs:
      - BotMonitoring
