version: 2.1
jobs:
  BotMonitoring:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Run Python script
          command: python3 main.py $CR_Uname_anand $CR_Pass_anand $GsheetMainID_anand
            $GsheetAlertID_anand $EID_anand $EPass_anand $4 $apikey
workflows:
  version: 2
  commit-workflow:
    version: 2
    jobs:
      - BotMonitoring:
          filters:
            branches:
              only:
                - anandkalejh
